In [1]:
import torch
import torch.nn.functional as F 
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
words = open('names.txt', 'r').read().splitlines()
words[:8]

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia']

In [4]:
chars = sorted(list(set(''.join(words))))
stoi = {s: i + 1 for i, s in enumerate(chars)}
stoi['.'] = 0
itos = {i: s for s, i in stoi.items()}
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [6]:
#building dataset

block_size = 3 #context length
X,Y = [],[]
for w in words[:5]:
   print(w)
   context = [0] * block_size
   for ch in w + '.' :
    ix = stoi[ch]
    X.append(context)
    Y.append(ix)
    print (''.join(itos[i] for i in context), '-->', itos[ix])
    context = context[1:] + [ix]

X = torch.tensor(X)
Y = torch.tensor(Y)



emma
... --> e
..e --> m
.em --> m
emm --> a
mma --> .
olivia
... --> o
..o --> l
.ol --> i
oli --> v
liv --> i
ivi --> a
via --> .
ava
... --> a
..a --> v
.av --> a
ava --> .
isabella
... --> i
..i --> s
.is --> a
isa --> b
sab --> e
abe --> l
bel --> l
ell --> a
lla --> .
sophia
... --> s
..s --> o
.so --> p
sop --> h
oph --> i
phi --> a
hia --> .


In [9]:
C = torch.randn((27,2))

In [25]:
emb = C[X]

In [20]:
C[X][13,2]

tensor([-0.9275,  0.6989])

In [22]:
C[1]

tensor([-0.9275,  0.6989])

In [23]:
w1 = torch.randn((6,100))
b1 = torch.randn(100)

In [33]:
torch.cat([emb[:,0,:], emb[:,1,:], emb[:,2,:]],1).shape

torch.Size([32, 6])

In [36]:
torch.cat(torch.unbind(emb,1), 1)

tensor([[-0.0124,  1.4213, -0.0124,  1.4213, -0.0124,  1.4213],
        [-0.0124,  1.4213, -0.0124,  1.4213, -1.1154, -2.1833],
        [-0.0124,  1.4213, -1.1154, -2.1833, -2.0468, -0.5038],
        [-1.1154, -2.1833, -2.0468, -0.5038, -2.0468, -0.5038],
        [-2.0468, -0.5038, -2.0468, -0.5038, -0.9275,  0.6989],
        [-0.0124,  1.4213, -0.0124,  1.4213, -0.0124,  1.4213],
        [-0.0124,  1.4213, -0.0124,  1.4213, -0.8791, -0.8578],
        [-0.0124,  1.4213, -0.8791, -0.8578, -0.2408,  1.6793],
        [-0.8791, -0.8578, -0.2408,  1.6793,  0.3415,  0.6112],
        [-0.2408,  1.6793,  0.3415,  0.6112,  0.8326, -0.2199],
        [ 0.3415,  0.6112,  0.8326, -0.2199,  0.3415,  0.6112],
        [ 0.8326, -0.2199,  0.3415,  0.6112, -0.9275,  0.6989],
        [-0.0124,  1.4213, -0.0124,  1.4213, -0.0124,  1.4213],
        [-0.0124,  1.4213, -0.0124,  1.4213, -0.9275,  0.6989],
        [-0.0124,  1.4213, -0.9275,  0.6989,  0.8326, -0.2199],
        [-0.9275,  0.6989,  0.8326, -0.2