In [1]:
import torch
import torch.nn.functional as F 
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
words = open('names.txt', 'r').read().splitlines()
words[:8]

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia']

In [4]:
chars = sorted(list(set(''.join(words))))
stoi = {s: i + 1 for i, s in enumerate(chars)}
stoi['.'] = 0
itos = {i: s for s, i in stoi.items()}
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [6]:
#building dataset

block_size = 3 #context length
X,Y = [],[]
for w in words[:5]:
   print(w)
   context = [0] * block_size
   for ch in w + '.' :
    ix = stoi[ch]
    X.append(context)
    Y.append(ix)
    print (''.join(itos[i] for i in context), '-->', itos[ix])
    context = context[1:] + [ix]

X = torch.tensor(X)
Y = torch.tensor(Y)



emma
... --> e
..e --> m
.em --> m
emm --> a
mma --> .
olivia
... --> o
..o --> l
.ol --> i
oli --> v
liv --> i
ivi --> a
via --> .
ava
... --> a
..a --> v
.av --> a
ava --> .
isabella
... --> i
..i --> s
.is --> a
isa --> b
sab --> e
abe --> l
bel --> l
ell --> a
lla --> .
sophia
... --> s
..s --> o
.so --> p
sop --> h
oph --> i
phi --> a
hia --> .


In [9]:
C = torch.randn((27,2))

In [25]:
emb = C[X]

In [20]:
C[X][13,2]

tensor([-0.9275,  0.6989])

In [22]:
C[1]

tensor([-0.9275,  0.6989])

In [23]:
w1 = torch.randn((6,100))
b1 = torch.randn(100)

In [48]:
h = emb.view(-1,6) @ w1 + b1

In [49]:
h

tensor([[-3.1032, -0.7460,  4.1123,  ..., -2.5229,  0.3644, -1.6054],
        [-3.5327,  3.3101,  0.8928,  ...,  3.1895, -7.7074, -5.3930],
        [-3.3314,  2.7302,  5.4719,  ...,  5.7826, -3.4945, -4.4694],
        ...,
        [ 3.0491, -2.0945, -2.1969,  ..., -2.1845,  8.6648,  0.4502],
        [ 0.9197,  0.9423, -4.6126,  ..., -2.1199,  0.8020,  0.4745],
        [-2.8487,  2.4194,  0.8942,  ..., -1.4049, -2.5574, -2.5979]])

In [50]:
h.shape

torch.Size([32, 100])

In [51]:
w2 = torch.randn([100,27])
b2 = torch.randn(27)

In [52]:
logits = h @ w2 + b2

In [53]:
logits.shape

torch.Size([32, 27])

In [54]:
logits

tensor([[  40.8006,   25.5408,   10.9606,   32.6616,  -23.3551,  -19.2810,
           71.4509,    9.0384,  -27.2935,   28.1369,  -13.8819,  -11.9292,
          -30.9930,   20.8293,  -21.5958,   21.9390,  -27.1963,    2.2436,
           -6.6520,  -13.4384,  -25.6438,    2.2993,   16.9792,    6.9525,
          -22.0759,   -4.5860,   49.8441],
        [  61.2546,   16.6125,   17.7567,   15.9647,   43.4062,  -36.5756,
           24.4442,    4.8349,   41.9174,   -3.4685,   19.4927,  -30.8003,
          -13.7138,   12.5741,   -4.1751,   32.2436,  -43.0172,   26.1243,
           79.4567,  -21.8631,  -18.3939,   -7.6246,   10.5778,   18.5261,
           -1.7561,    1.4011,   46.7418],
        [  16.3238,  -24.3133,   -5.5370,    5.8532,   12.7041,  -55.1855,
          -60.2174,   40.4092,   12.5923,    7.7951,   15.6492,  -14.9819,
           -8.4088,   -9.0175,  -27.9398,  -30.4346,   21.4738,   57.9507,
            6.1736,    4.2230,   14.5298,    9.0414,  -35.4855,   46.5545,
          -21.